// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSessionLogs():Promise<Array<main.SessionLog>>;

export function GetSettings():Promise<main.Settings>;

export function Ping():Promise<string>;

export function SaveSettings(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean,arg6:boolean):Promise<void>;

export function StartTimer(arg1:number,arg2:string):Promise<void>;

export function StopTimer():Promise<void>;
