// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessionLogs() {
  return window['go']['main']['App']['GetSessionLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartTimer(arg1, arg2) {
  return window['go']['main']['App']['StartTimer'](arg1, arg2);
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}
